version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
      timezone: 'EST5EDT'
    open-pull-requests-limit: 10
    groups:
      fontawesome:
        patterns:
          - '@fortawesome/*'
      eslint-plugins: # TODO Add eslint back once updated to v9
        patterns:
          - '@shlinkio/eslint-config-js-coding-standard'
          - 'typescript-eslint'
          - '*eslint-plugin*'
      shlink:
        patterns:
          - '@shlinkio/*'
      types:
        patterns:
          - '@types/*'
      testing:
        patterns:
          - '@testing-library/*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      workbox:
        patterns:
          - 'workbox*'
    ignore:
      # Bootstrap can introduce visual breaking changes on styles
      # Ignore it, since the plan is to remove it anyway
      - dependency-name: 'bootstrap'
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
      timezone: 'EST5EDT'
