name: shlink web client continuous deployment

on:
  push:
    branches:
      - main
      - develop
  deployment:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
    build_and_deploy_job:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
    
            - name: MinVer
              id: minver
              uses: theantitwink/minver@main

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '22'
    
            - name: Install dependencies
              run: npm install --force
    
            - name: Build
              run: npm run build:dist
              env:
                VERSION: ${{ steps.minver.outputs.version }}

            # - name: Update package version
            #   uses: theantitwink/update-package-version@main
            #   with:
            #     version: ${{ steps.minver.outputs.version }}
    
            - name: Build And Deploy
              id: deploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_SKY_012BE680F }}
                repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                action: "upload"
                ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                app_location: "/build" # App source code path
                api_location: "" # Api source code path - optional
                output_location: "build" # Built app content directory - optional
                ###### End of Repository/Build Configurations ######
                skip_app_build: true

        environment:
          name: gray-sky
          url: ${{ steps.deploy.outputs.static_web_app_url }}
