name: shlink web client continuous deployment

on:
  push:
    branches:
      - main
      - develop

concurrency:
  group: shlink-web-client
  cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
    
            - name: Install dependencies
              run: npm ci
    
            - name: Build
              run: npm run build
    
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
                publish_branch: gh-pages
                cname: shlink.io
                commit_message: "Deployed from ${{ github.sha }}"
                allow_empty_commit: true
                force_orphan: true
                clean: true
                enable_jekyll: false
                keep_files: true
                user_name: shlink
                user_email: